pct create 100 /var/lib/vz/template/cache/debian-12-standard_12.12-1_amd64.tar.zst \
  --arch amd64 \
  --hostname BOOKSTACK \
  --cores 2 \
  --memory 2048 \
  --swap 512 \
  --net0 name=eth0,bridge=vmbr0,firewall=1,gw=192.168.1.1,ip=192.168.1.100/24 \
  --rootfs local-lvm:20 \
  --unprivileged 1 \
  --features nesting=1 \
