pct create 112 /var/lib/vz/template/cache/ubuntu-24.04-standard_24.04-2_amd64.tar.zst \
  --arch amd64 \
  --hostname NAME \
  --cores 2 \
  --memory 2048 \
  --swap 512 \
  --net0 name=eth0,bridge=vmbr0,firewall=1,gw=192.168.1.1,ip=192.168.1.112/24 \
  --rootfs local-lvm:20 \
  --unprivileged 1 \
  --features nesting=1
