arch: amd64
cores: 4
features: nesting=1
hostname: PLEXMEDIASERVER
memory: 4096
mp0: /mnt/Multimedia_NAS/Movies,mp=/media/movies
mp1: /mnt/Multimedia_NAS/Series,mp=/media/series
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.1.1,hwaddr=BC:24:11:7C:5E:F5,ip=192.168.1.104/24,type=veth
ostype: ubuntu
rootfs: local-lvm:vm-104-disk-0,size=20G
swap: 512
unprivileged: 1
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
lxc.mount.entry: /dev/fb0 dev/fb0 none bind,optional,create=file
lxc.idmap: u 0 100000 65536
lxc.idmap: g 0 100000 993
lxc.idmap: g 993 993 1
lxc.idmap: g 994 100994 64542
