server {
    listen 6875;
    server_name _; # Le "_" signifie qu'il répond à l'IP du conteneur

    root /var/www/bookstack/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
    }

    # Sécurité supplémentaire pour les fichiers .env et .git
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
